import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<p className={styles.description}></p>

				<div className={styles.grid}>
					<a href="https://nextjs.org/docs" className={styles.card}>
						<Image src="/images/aa.png" alt="" height="300" width="300"/>
					</a>
					<a href="https://nextjs.org/docs" className={styles.card}>
						<Image src="/images/aaa.png" alt="" height="300" width="300"/>
					</a>
				</div>
			</main>
		</div>
	);
}
